Auto assign only 1 person from list of `persons` or the first team specified in `teams`
rowi1de/auto-assign-review-teams pull request #24
Opened 2020-09-02 22:46 UTC by michellelimxuanli

## Changes
Created an optional boolean parameter `pick-one-from-persons-or-team` if users would like for one team member to be picked for assignment for each PR

Also updated the npm packages and used the latest Octokit methods

## Motivation
When we used the original `teams` method, our entire Github reviewers team was notified every time a PR was open, even though we did pick "round robin" and only assigned one reviewer each time. 

Therefore we created a way to only assign one reviewer from a Github team or list of persons at a time. Say no more to your entire team being spammed every time a PR is opened. 

## Testing

- Functionality of `pick-one-from-persons-or-team=true` works when our org is using this forked version. One reviewer is assigned each time from our Github team.
- The original unit tests still pass.
- But I'd love for someone to add a new unit test for `pick-one-from-persons-or-team=true`

2020-09-03 05:29 UTC, rowi1de commented
Hey thanks for the PR. Will review soon.
Regarding the team notification: Did you Check  the box „don’t notify team“?
https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team
https://docs.github.com/assets/images/help/teams/review-assignment-notifications.png

2020-09-03 06:59 UTC, rowi1de approved these changes
Thanks for the contribution, will release a new version after merge

2020-09-03 16:13 UTC, michellelimxuanli commented
> Thanks for the contribution, will release a new version after merge

Awesome! Btw for the new setting, I forgot to remove PR author from the Github Team list. Have made another commit and will open a PR again once the current PR is merged.

> Regarding the team notification: Did you Check the box „don’t notify team“?

Yes, we had already checked the box.

2020-09-07 17:10 UTC, rowi1de commented
Somehow the tests are failing

2020-09-14 07:58 UTC, rowi1de commented on .github/workflows/test.yml
> +          teams: "no-team"
this needs to be removed

2020-09-14 07:59 UTC, rowi1de requested changes
Please remove team from test.yml

2021-12-08 20:28 UTC, rowi1de commented
@michlimlim let's finish this, I recently upgraded to GHA 5.0.0

2021-12-08 21:29 UTC, rowi1de commented
https://github.com/rowi1de/auto-assign-review-teams/pull/58

2021-12-08 21:29 UTC, closed without merging